services:
  postgres:
    image: postgres:16
    container_name: tmapi-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tmapi_db
    ports:
      - "5433:5432"
    volumes:
      - tmapi_postgres_data:/var/lib/postgresql/data

  api:
    build:
      context: ./TMAPI_Backend
    container_name: tmapi-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Development"
    depends_on:
      - postgres

volumes:
  tmapi_postgres_data: